[Sky]
Temperature = 8

[4KCL]
Temperature = 8
RL = -40

[Window]
Temperature = 300
RL = -20
IL = -0.01

[IRfilter]
Temperature = 50
RL = -25
IL = -0.003

[FeedHornSky]
Temperature = 5
RL = -30
IL = -0.05

[OMTsky]
Temperature = 5
RL = -25
IL = -0.1

[FeedHornload]
Temperature = 5
RL = -30
IL = -0.05

[OMTload]
Temperature = 5
RL = -25
IL = -0.1

[Hybridsky]
Temperature = 5
RL = -25
IL = -0.1

[Hybridload]
Temperature = 5
RL = -25
IL = -0.1

[LNA1]
Tnoise = 3.8
RL = -15
Gain = 28

[LNA2]
Tnoise = 3.8
RL = -15
Gain = 28

[LNA3]
Tnoise = 3.8
RL = -15
Gain = 28

[LNA4]
Tnoise = 3.8
RL = -15
Gain = 28

[SPO]
Window = -20
IRfilter = -20
4KCL = -48.5

[Environment]
Tenv1 = 50.1
Tenv2 = 5.1
Tfpga = 0
Tcryo1 = 300
Tcryo2 = 50
Tcryo3 = 5
